ALTER TABLE modulos DROP COLUMN IF EXISTS fechainicio;
ALTER TABLE modulos DROP COLUMN IF EXISTS "fechaInicio";
ALTER TABLE modulos ADD COLUMN "fechaInicio" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
